# Collector specific configuration
base_url: "https://floodforecasting.googleapis.com/v1"

dataset_info:
  name: "google-floods-significant-events"
  title: "Significant Flood Events"
  resource_name: "significant_flood_events.csv"
  resource_description: "Significant flood events starting on {start_date}"
  tags:
    - "flooding"
    - "natural disaster"
