# Collector specific configuration
base_url: "https://floodforecasting.googleapis.com/v1"

dataset_info:
  name: "google-floods-significant-events"
  title: "Significant Flood Events"
  resource_name: "significant_flood_events"
  csv_resource_description: "Significant flood events starting on {start_date}"
  json_resource_description: "Significant flood event geometry starting on {start_date}"
  custom_viz: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi985o5uvW39heXyD2OdJwYCXBHokt5ef7vd4cBH4wRAwOry-6QWZ8p51RtLJeqanho7OGAtAX0ZvKqOUESmx-VJkZJiyAEcYJx2E5zVZiWE23cEukRj7VL6rJz4ygnt1EjbOa5Q05gW-P7vpqtvT1QGam6xdP5EaC9oBvMUJHeZX4gvC_b0n3GyoF5/s1280/Flood%20Hub%20-%20models.jpg"
  headers:
    - startTime
    - minimumEndTime
    - endTime
    - affectedCountryCodes
    - affectedCountryISO3s
    - affectedPopulation
    - areaKm2
    - gaugeIds
    - eventPolygonId
    - eventTrackingIds
    - dateRetrieved
  tags:
    - "flooding"
    - "natural disaster"
